---
# ------------------------------------------------------------
# ServiceAccount
# ------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-app: cluster-autoscaler
    k8s-addon: cluster-autoscaler.addons.k8s.io

---
# ------------------------------------------------------------
# ClusterRole
# ------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
  labels:
    k8s-app: cluster-autoscaler
    k8s-addon: cluster-autoscaler.addons.k8s.io
rules:
  # Events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # Endpoints
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["create", "patch"]

  # Pods
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update"]

  # Nodes (scale up/down)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "get", "update", "patch"]

  # Core resources
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["watch", "list", "get"]

  # Apps (NO extensions API)
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - replicasets
      - daemonsets
    verbs: ["watch", "list", "get"]

  # PDBs (policy/v1)
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["watch", "list"]

  # Storage
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csinodes
      - csidrivers
      - csistoragecapacities
    verbs: ["watch", "list", "get"]

  # Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]

  # Leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]

---
# ------------------------------------------------------------
# Role (ConfigMaps)
# ------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-app: cluster-autoscaler
    k8s-addon: cluster-autoscaler.addons.k8s.io
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "list", "watch", "get", "update", "delete"]

---
# ------------------------------------------------------------
# ClusterRoleBinding
# ------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
  labels:
    k8s-app: cluster-autoscaler
    k8s-addon: cluster-autoscaler.addons.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
# ------------------------------------------------------------
# RoleBinding
# ------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-app: cluster-autoscaler
    k8s-addon: cluster-autoscaler.addons.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
# ------------------------------------------------------------
# Deployment
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - name: cluster-autoscaler
          image: chandrakant3007/cluster-autoscaler:1.33.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /cluster-autoscaler
            - --cloud-provider=cloudstack
            - --cloud-config=/config/cloud-config
            - --nodes=<MIN>:<MAX>:<CLOUDSTACK-CLUSTER-ID>
            - --scan-interval=10s
            - --scale-down-enabled=true
            - --v=4
          volumeMounts:
            - name: cloud-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: cloud-config
          secret:
            secretName: cloudstack-secret

